### ISSUE TITLE
TODO: CSS

### ISSUE THREAD

**Issue by vlbee** [fac-13/VP-react-game#15]
- [ ]   blinking cursor for input field
- [x]   blinking heart animation in motivation levels
- [ ]   transformation on buttons so emojis move when buttons are depressed
